CREATE TABLE PRE_DEFINED_SYSTEM_NOTES(
	BODY TEXT NOT NULL,
	MIN_VALUE INT NOT NULL,
	MAX_VALUE INT NOT NULL
);

CREATE TABLE SYSTEM_NOTES(
	EMAIL VARCHAR(200) NOT NULL,
	BODY TEXT NOT NULL,
	DATE DATE NOT NULL,
	FOREIGN KEY (EMAIL) REFERENCES USER(EMAIL)
);

INSERT INTO PRE_DEFINED_SYSTEM_NOTES VALUES('Pre Defined Note for 1 < value <= 10', 1, 10);

INSERT INTO PRE_DEFINED_SYSTEM_NOTES VALUES('Pre Defined Note for 10 < value <= 15', 10, 15);

INSERT INTO PRE_DEFINED_SYSTEM_NOTES VALUES('Pre Defined Note for 15 < value <= 20', 15, 20);

INSERT INTO PRE_DEFINED_SYSTEM_NOTES VALUES('Pre Defined Note for 20 < value', 20, 10000);

commit;